export { default as Header } from "./Header/Header";
export { default as Footer } from "./Footer/Footer";
export { default as Landing } from "./Landing/Landing";
export { default as About } from "./About/About";
export { default as Contact } from "./Contact/Contact";
export { default as Experience } from "./Experience/Experience";
export { default as Project } from "./Project/Project";
export { default as SocialMedia } from "./SocialMedia/SocialMedia";
export { default as CustomRight } from "./CustomRight/CustomRight";
