import Head from "next/head";
import Layout from "../Layout/Layout";
import { Header, CustomRight, SocialMedia } from "../components";

export default function Home() {
  return (
    <>
      <Header />
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </Layout>
      <SocialMedia />
      <CustomRight />
    </>
  );
}
