import Head from "next/head";
import Layout from "../Layout/Layout";
import { Header, CustomRight, SocialMedia, Landing } from "../components";

//TODO - Module path aliases
//TODO - SEO
//TODO - Image optimizer
//TODO - Contact form
//TODO - Finish Landing page
//TODO - Resume like experiences
//TODO - About me
//TODO - Projects
//TODO - e2e Cypress
//TODO - Review / last Refactor
//TODO - Git push master + workflow

export default function Home() {
  return (
    <>
      <Header />
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon/favicon.ico" />
        </Head>
        <Landing />
      </Layout>
      <SocialMedia />
      <CustomRight />
    </>
  );
}
