import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Test h1</h1>
        <h2>Test h2</h2>
        <h3>Test h3</h3>
        <h4>Test h4</h4>
        <h5>Test h5</h5>
        <p>Paragraph</p>
      </main>

      <footer>Footer</footer>
    </div>
  );
}
